# These are supported funding model platforms
github: [JoaquinAmatRodrigo, JavierEscobarOrtiz]

custom: ["https://www.buymeacoffee.com/skforecast", "https://www.paypal.com/donate/?hosted_button_id=D2JZSWRLTZDL6"]
