name: Unit Tests

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install libomp on macOS
        if: matrix.platform == 'macos-latest'
        run: |
          brew install libomp
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tomli
        python extract_dependences.py
        python -m pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest -vv
